# version: 1-alpha.1

# releases:
#   vega-template-testing:
#     name: VEGA Project name
#     autodeploy-on: default
#     chart: csssr/static-site@~1.0.0
#     static-params:
#       projectID: vega-template
#     builds:
#       - workflow: build-static.yaml
#         values:
#           buildID: build-{{ .Build.RunID }}
